### ISSUE TITLE
GET Chapters API not working

### ISSUE THREAD

**Issue by aravindputrevu** [vedicscriptures/bhagavad-gita-api#1]
Chapter's API does not seem to work. 

**To Reproduce**
1. Query the chapters using browser https://vedicscripturesapi.herokuapp.com/chapters
2. Error "Cannot GET /chapters" appears

**Expected behavior**
A list of Chapters should appear

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome
 - Version 10.15.7

**Comment by PtPrashantTripathi** [comment]
#### Hey @aravindputrevu thanks for your feedback.
✋`Now it's working fine, try`

GET [/gita/chapters](https://vedicscripturesapi.herokuapp.com/gita/chapters)
![IMG_20201121_234910](https://user-images.githubusercontent.com/26687933/99884502-b033ec80-2c54-11eb-91e8-84b1d6b26490.jpg)

> Acculty the server and API was working fine, there was just minor typo in [Documentation](https://github.com/vedicscriptures/bhagavad-gita-api#readme)

#### Now it's *fixed*🔧
