### ISSUE TITLE
Getting wrong SVG

### ISSUE THREAD

**Issue by sauravgpt** [vedicscriptures/bhagavad-gita-api#11]
**Describe the bug**

**To Reproduce**
1. Go to https://bhagavadgitaapi.in/gita.svg/1/1
2. Then it must respond with SVG of Chapter 1 and Slok 1
3. But I'm getting random SVG

**Expected behavior**
It must respond with correct SVG.

**Screenshots**
![image](https://user-images.githubusercontent.com/28841505/122700087-3f939380-d268-11eb-990b-28caddd37b30.png)

**Comment by PtPrashantTripathi** [comment]
Buddy for svg you have to send ch and sl values into the query not via param

Read this https://docs.bhagavadgitaapi.in/api-reference/get-gita.svg you will get it

**Comment by sauravgpt** [comment]
Ups my bad! Thanks
