### ISSUE TITLE
Can I get a the collections copy from mongodb 

### ISSUE THREAD

**Issue by scshiv29-dev** [vedicscriptures/bhagavad-gita-api#14]
I want to learn and try to make an api myself ,it would be super helpful if you could give me the data used to populate the database.

**Comment by PtPrashantTripathi** [comment]
> I want to learn and try to make an api myself ,it would be super helpful if you could give me the data used to populate the database.

The link of the books and source are given in readme file.

You can go through the collect the data your self and do some ETL work.

Try and learn
