### ISSUE TITLE
docs unreachable

### ISSUE THREAD

**Issue by JavaToGo** [vedicscriptures/bhagavad-gita-api#15]
**Describe the bug**
Getting a 404 error when trying to access https://docs.bhagavadgitaapi.in

**To Reproduce**
1. Go to 'https://docs.bhagavadgitaapi.in'
2. See error

**Expected behavior**
User should be able to access the documentation page.

**Screenshots**
<img width="653" alt="image" src="https://user-images.githubusercontent.com/13631831/166169470-1d4df13b-8124-4794-bae1-4df826584614.png">

**Desktop (please complete the following information):**
 - OS: [macOS Monterey]
 - Browser [chrome and safari]
 - Version [latest]

**Comment by PtPrashantTripathi** [comment]
Bug noted, I'll to fix this soon

**Meanwhile you can see the basic docs from GitHub readme or refer to tutorial video**
![Screenshot_2022-05-02-06-30-46-808_com android chrome](https://user-images.githubusercontent.com/26687933/166172727-f215356e-2bb0-4d73-a53a-a1c8eccc0876.jpg)

**Comment by JavaToGo** [comment]
Thanks. I am trying to get to the Google Form to request an API key. Can you provide that link here please?

**Comment by PtPrashantTripathi** [comment]
On 29 Mar, 2022 we have removed API key requirment, you can directly use our api without any key.
