### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by amnjain** [vedicscriptures/bhagavad-gita-api#2]
Hi, can u please check ur Heroku error log because the site is showing "Application Error"

<img width="954" alt="gita" src="https://user-images.githubusercontent.com/31520438/100077350-41c77800-2e68-11eb-9bf9-501a4b8df4c0.PNG">

**Comment by amnjain** [comment]
Now It's working but check once why this gives an application error sometimes.

**Comment by PtPrashantTripathi** [comment]
Acculty we are using heroku free ☁️ cloud server,
It's has limited bandwidth ☹️ that why it's shows 🐞error sometimes...
