### ISSUE TITLE
Not able to fetch data from Flutter app

### ISSUE THREAD

**Issue by mishraaditya595** [vedicscriptures/bhagavad-gita-api#20]
**Describe the bug**
I am trying to build a Flutter app using your API. But when I am calling the API, instead of a JSON response, I am getting a script as a string. But, it works fine if I hit the URL in the browser.

**Expected behavior**
Response in the browser:
<img width="1440" alt="Screenshot 2022-12-09 at 4 45 17 PM" src="https://user-images.githubusercontent.com/54946784/206690515-0e58debd-1f02-49ef-a3bb-e41583e46bba.png">

Response when called from the Flutter (Dart) code.
<img width="711" alt="Screenshot 2022-12-09 at 4 47 33 PM" src="https://user-images.githubusercontent.com/54946784/206690800-0bad07fe-0cb3-42d1-b4e4-a9ee71337420.png">

**Dart Code**
<img width="501" alt="Screenshot 2022-12-09 at 4 53 02 PM" src="https://user-images.githubusercontent.com/54946784/206691745-86b2fe57-7add-4f36-93c0-e72adc6f12eb.png">

Any help will be appreciated.

**Comment by PtPrashantTripathi** [comment]
Hi @mishraaditya595 
Please follow this soultion 
https://github.com/vedicscriptures/bhagavad-gita-api/discussions/3#discussioncomment-3475907

Hope it will work for you as well.
