### ISSUE TITLE
Audio file for shlokas

### ISSUE THREAD

**Issue by nishp77** [vedicscriptures/bhagavad-gita-api#21]
Well no way to reach out to you directly, but this is super great to see this project, plus vedic language. To be honest I don't know anything about my native language like I can only speak don't know how to write or read so yeah it going to be really amazing for me.

Thanks to Krishna I found this project, for many days I wanted to try an experiment on randomness, though we know random is not random in programming, I was like deep down to atomic level His there as well so experiment Gita's Shloka and we relate that to our journey of each day how's going to be like and we write the thoughts on it at the end of the day.

**Comment by PtPrashantTripathi** [comment]
Hi @nishp77
Thanks for the support 💕 we appreciate it,

If any time you would like to connect with me just ping me on any of my social media accounts


Instagram: https://instagram.com/ptprashanttripathi

Telegram: https://t.me/ptprashanttripathi
