### ISSUE TITLE
demo link doesn't work

### ISSUE THREAD

**Issue by kirandash** [vedicscriptures/bhagavad-gita-api#30]
**Describe the bug**
Demo link: https://docs.bhagavadgitaapi.in/ does not work.

**Screenshots**

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/13310363/233784880-441f978f-d0dd-4bd1-904b-2a8662451d41.png">

**Comment by PtPrashantTripathi** [comment]
Thanks for informing.it is working now

**Comment by kirandash** [comment]
it just redirects back to https://bhagavadgitaapi.in/

**Comment by PtPrashantTripathi** [comment]
It's what it suppose to doPreviously docs and api were deployed but different serversdocs : docs.bhagavadgitaapi.inapi: bhagavadgitaapi.inBut then I have marged them together in bhagavadgitaapi.inAnd setuped a redirect docs.bhagavadgitaapi.in to bhagavadgitaapi.inOn 22-Apr-2023 8:18 pm, Kiran Dash ***@***.***> wrote:
it just redirects back to https://bhagavadgitaapi.in/
