### ISSUE TITLE
404 error with https://bhagavadgitaapi.in/api/v1

### ISSUE THREAD

**Issue by priyansxu** [vedicscriptures/bhagavad-gita-api#35]
const response = await fetch(`https://bhagavadgitaapi.in/api/v1/chapter/${chapter}/verse/${verse}`);
      const geeta = await response.json();

      const shlok = geeta.data.slok;
      const tej = geeta.data.tej.ht;
      const trans = geeta.data.siva.et;

Its show an error: ```FetchError: invalid json response body at https://bhagavadgitaapi.in/api/v1/chapter/2/verse/8 reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON```

**Comment by Web403** [comment]
Instead of This => ```https://bhagavadgitaapi.in/api/v1/chapter/${chapter}/verse/${verse}``` 
Use This  =>```https://bhagavadgitaapi.in/slok/${chapter}/${verse}/```

**Comment by priyansxu** [comment]
I fixed the issue, thanks for your help!

**Comment by PtPrashantTripathi** [comment]
Clossing the Issue
