### ISSUE TITLE
This is not working anymore

### ISSUE THREAD

**Issue by Balram-Parmar** [vedicscriptures/bhagavad-gita-api#41]
**Describe the bug**
I would like to say this is a wonderful api if you can get it back as it is not working anymore. I sent a req at "https://bhagavadgitaapi.in/chapters/4" and other chapters too but it  is returning 404.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PtPrashantTripathi** [comment]
https://bhagavadgitaapi.in/chapter/4/

This is correct url

**Comment by Balram-Parmar** [comment]
Yes, my mistake, and i realized it later and  closed the issue
