### ISSUE TITLE
all shloks of a chapter

### ISSUE THREAD

**Issue by rishabhagg7** [vedicscriptures/bhagavad-gita-api#47]
**Is your feature request related to a problem? Please describe.**
I want to display all shloks when user clicks on a chapter. To do so I have to make separate api calls for every shlok of the chapter. Due to this I am not able to do pagination and due to several api calls, it is taking too much time to load. 

**Describe the solution you'd like**
It would be good if there is a direct endpoint which returns the list of shloks of a particular chapter. The end point can have parameter of chapter number. Further another parameter to request list of shloks of particular translation only to make result less bulky can be added.

**Comment by PtPrashantTripathi** [comment]
Sure,

To implement pagination for chapter details and slok (verse) counts, follow these steps:

1. **Fetch Chapter Details**: Call the endpoint to retrieve the details of the chapter and its verse count:

   ```
   GET https://vedicscriptures.github.io/chapters
   ```

   The response will contain the total number of verses in `result["verses_count"]`.

2. **Pagination Logic**: On the chapter page, display a maximum of 5 to 10 verses per page. To achieve this, implement pagination with a step size of 5 or 10.

3. **Fetch Verses**: For a given page number, fetch the corresponding verses. For example, for page number 1, run a loop from 1 to 5 and call the slok endpoint as follows:

   ```
   GET https://vedicscriptures.github.io/slok/:ch/:sl
   ```

   Here, `:ch` is the chapter number, and `:sl` is the verse number calculated using the formula: `Page_number * 5 + i`.

Example for page number 1 (displaying 5 verses per page):

- Page number 1:
  - Loop from 1 to 5
  - Call `https://vedicscriptures.github.io/slok/:ch/:sl` where `:sl` is calculated as `1*5 + i` for `i` in the range 1 to 5. 

This approach will ensure you display a maximum of 5 to 10 verses per page, allowing users to navigate through the verses seamlessly.
