### ISSUE TITLE
Server requests are responding with an error.

### ISSUE THREAD

**Issue by sagarbhosale** [vedicscriptures/bhagavad-gita-api#9]
**Describe the bug**
All requests are failing.

**To Reproduce**
```
curl https://vedicscripturesapi.herokuapp.com/gita
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /gita</pre>
</body>
</html>
```

**Additional context**
It was working until yesterday.

**Comment by PtPrashantTripathi** [comment]
> @sagarbhosale kindly refer to the documentation 
https://docs.bhagavadgitaapi.in/api-reference/get-slokm

**Comment by PtPrashantTripathi** [comment]
Hi @sagarbhosale  did you got my mail
I have sent you api key
